# Open source project: Enterprise-.Net-Architecture-Template -  CRAFTED BY LUIS LÃ“PEZ (https://github.com/luislopez-dev)

services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "%uuuuiiiPPPPCCC555555555"
    ports:
      - "1401:1433"
    networks:
      - net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:5000"
    environment:
      - ConnectionStrings__app=Server=sqlserver;Database=AppDb;User Id=sa;Password=%uuuuiiiPPPPCCC555555555;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000      
    networks:
      - net

networks:
  net:
