name: Build, Test and Publish Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build-and-test:

    runs-on: Ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
      
      - name: Restore dependencies for Presentation
        run: dotnet restore "Src/Presentation/Presentation.csproj"

      - name: Restore dependencies for Application
        run: dotnet restore "Src/Application/Application.csproj"

      - name: Restore dependencies for Infrastructure
        run: dotnet restore "Src/Infrastructure/Infrastructure.csproj"

      - name: Restore dependencies for Domain
        run: dotnet restore "Src/Domain/Domain.csproj"

      - name: Restore dependencies for Presentation.Tests
        run: dotnet restore "Tests/Presentation.Tests/Presentation.Tests.csproj"

      - name: Restore dependencies for Application.Tests
        run: dotnet restore "Tests/Application.Tests/Application.Tests.csproj"

      - name: Restore dependencies for Infrastructure.Tests
        run: dotnet restore "Tests/Infrastructure.Tests/Infrastructure.Tests.csproj"

      - name: Restore dependencies for Domain.Tests
        run: dotnet restore "Tests/Domain.Tests/Domain.Tests.csproj"

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --logger trx --collect:"XPlat Code Coverage" --filter "Category!=E2E

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t "${{secrets.DOCKER_HUB_USERNAME}}/dotnet-app:latest" . --push
